### ISSUE TITLE
`flatten` should use `addCallStackToException`

### ISSUE THREAD

**Issue by glasserc** [parsonsmatt/annotated-exception#23]
Currently it just concatenates annotations using `(++)`, which means we can get two `CallStack` annotations in an exception.

**Comment by parsonsmatt** [comment]
Can you post a demonstration? I tried to ensure that the API in the library preserved the right invariants, so if I know where the problem is, then that makes it easier to diagnose. Thanks!

**Comment by glasserc** [comment]
I wasn't exactly sure what qualified as the API in the library but I wrote a few test cases demonstrating the problem in the linked PR.
